'''Configurations.
'''

#GENERAL CONFIGURATIONS
DEVICE='gpu'
MODEL_SAVE_FOLDER='./artifacts/'
GRAPH_SAVE_FOLDER='./graphs/'

#DATASET CONFIGURATIONS
BATCH_SIZE=128
IMAGE_WIDTH=32
IMAGE_HEIGHT=32
IMAGE_CHANNEL=3
SHUFFLE=True
PATCH_SIZE=8
NUM_WORKERS=4
RANDOM_ROTATION=20


#MODEL CONFIGURATIONS
TRANSFORMER_NETWORK_DEPTH=6
NUM_CLASSES=10
PROJECTION_DIM_KEYS=128
PROJECTION_DIM_VALUES=256
NUM_HEADS=8
ATTN_DROPOUT_PROB=0.1
FEEDFORWARD_PROJECTION_DIM=512
FEEDFORWARD_DROPOUT_PROB=0.1

#TRAINING CONFIGURATIONS
TRAIN_EPOCH=500
LEARNING_RATE=0.0001
SCHEDULER_GAMMA=0.7
SCHEDULER_STEP_SIZE=50




